
Style/ClassAndModuleChildren:
  Enabled: false

Style/TrailingBlankLines:
  Enabled: false

# New to 0.39.x

Style/NestedParenthesizedCalls:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.3

# FIXME: This probably should get added to all 48 files. Blech.

Style/FrozenStringLiteralComment:
  Enabled: false
